import { useCallback, useEffect, useState } from 'react';
import { toast } from 'sonner';
import { productsApi } from '../../products/api/productsApi';
import { customersApi } from '../../customers/api/customersApi';
import { HeldOrdersModal } from '../components/HeldOrdersModal';
import { PaymentModal } from '../components/PaymentModal';
import { PosCart } from '../components/PosCart';
import { PosProductGrid } from '../components/PosProductGrid';
import { QuickCustomerModal } from '../components/QuickCustomerModal';
import { ReceiptModal } from '../components/ReceiptModal';
import { posApi } from '../api/posApi';

export function PosPage() {
  const [cartItems, setCartItems] = useState([]); const [selectedCustomer, setSelectedCustomer] = useState(null); const [overallDiscount, setOverallDiscount] = useState(0); const [heldOrders, setHeldOrders] = useState([]);
  const [productsData, setProductsData] = useState(null); const [categories, setCategories] = useState([]); const [customers, setCustomers] = useState([]); const [isProductsLoading, setIsProductsLoading] = useState(true); const [isCheckoutLoading, setIsCheckoutLoading] = useState(false);
  const [isPaymentModalOpen, setIsPaymentModalOpen] = useState(false); const [isReceiptModalOpen, setIsReceiptModalOpen] = useState(false); const [isQuickCustomerOpen, setIsQuickCustomerOpen] = useState(false); const [isHeldOrdersOpen, setIsHeldOrdersOpen] = useState(false); const [lastCompletedSale, setLastCompletedSale] = useState(null);
  const refreshProducts = useCallback(async () => { try { setProductsData(await productsApi.getProducts({ per_page: 250 })); } catch { toast.error('فشل تحميل المنتجات'); } finally { setIsProductsLoading(false); } }, []);
  const refreshCategories = useCallback(async () => { try { setCategories(await productsApi.getCategories()); } catch { setCategories([]); } }, []);
  const refreshCustomers = useCallback(async () => { try { setCustomers(await customersApi.getQuickList()); } catch { setCustomers([]); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void refreshProducts(); void refreshCategories(); void refreshCustomers(); }, 0); return () => window.clearTimeout(timer); }, [refreshProducts, refreshCategories, refreshCustomers]);
  const playBeep = () => { try { const AudioContextClass = window.AudioContext || window.webkitAudioContext; const context = new AudioContextClass(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.type = 'sine'; oscillator.frequency.value = 880; gain.gain.setValueAtTime(0.1, context.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, context.currentTime + 0.12); oscillator.connect(gain); gain.connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + 0.12); } catch { /* Audio can be blocked before a user gesture. */ } };
  const addToCart = useCallback((product) => { playBeep(); setCartItems((current) => { const existing = current.find((item) => item.product.id === product.id); const unitPrice = Number(product.selling_price); const taxPercent = Number(product.tax_percent || 15); if (existing) { const quantity = existing.quantity + 1; const beforeTax = unitPrice * quantity - existing.discount_amount; const taxAmount = Number(((beforeTax * taxPercent) / 100).toFixed(2)); return current.map((item) => item.product.id === product.id ? { ...item, quantity, tax_amount: taxAmount, subtotal: beforeTax + taxAmount } : item); } const taxAmount = Number(((unitPrice * taxPercent) / 100).toFixed(2)); return [...current, { product, quantity: 1, unit_price: unitPrice, discount_amount: 0, tax_percent: taxPercent, tax_amount: taxAmount, subtotal: unitPrice + taxAmount }]; }); }, []);
  const handleBarcodeSubmit = async (barcode) => { const found = productsData?.data?.find((product) => product.barcode === barcode); if (found) { addToCart(found); toast.success(`تمت إضافة: ${found.name}`); return; } try { const product = await productsApi.findByBarcode(barcode); addToCart(product); toast.success(`تمت إضافة: ${product.name}`); } catch { toast.error(`لم يتم العثور على أي منتج بالباركود: ${barcode}`); } };
  const updateQuantity = (productId, quantity) => { if (quantity <= 0) { setCartItems((current) => current.filter((item) => item.product.id !== productId)); return; } setCartItems((current) => current.map((item) => { if (item.product.id !== productId) return item; const beforeTax = item.unit_price * quantity - item.discount_amount; const taxAmount = Number(((beforeTax * item.tax_percent) / 100).toFixed(2)); return { ...item, quantity, tax_amount: taxAmount, subtotal: beforeTax + taxAmount }; })); };
  const [isClearConfirmOpen, setIsClearConfirmOpen] = useState(false);
  const clearCart = () => { if (cartItems.length) setIsClearConfirmOpen(true); };
  const confirmClearCart = () => { setCartItems([]); setOverallDiscount(0); setSelectedCustomer(null); setIsClearConfirmOpen(false); };
  const holdOrder = () => { if (!cartItems.length) return; setHeldOrders((current) => [{ id: Math.random().toString(36).substring(2, 9), timestamp: new Date().toLocaleTimeString('ar-SA', { hour: '2-digit', minute: '2-digit' }), customerName: selectedCustomer?.name, items: [...cartItems], overallDiscount, total: cartItems.reduce((sum, item) => sum + item.subtotal, 0) - overallDiscount }, ...current]); setCartItems([]); setOverallDiscount(0); setSelectedCustomer(null); toast.info('تم تعليق الفاتورة بنجاح'); };
  const resumeOrder = (order) => { if (cartItems.length) holdOrder(); setCartItems(order.items); setOverallDiscount(order.overallDiscount); setHeldOrders((current) => current.filter((item) => item.id !== order.id)); toast.success('تمت استعادة الفاتورة المعلقة'); };
  const checkout = async (paymentData) => { const payload = { customer_id: paymentData.customer_id, discount_amount: overallDiscount, notes: paymentData.notes, items: cartItems.map((item) => ({ product_id: item.product.id, quantity: item.quantity, discount_amount: item.discount_amount })), payments: paymentData.payments }; try { setIsCheckoutLoading(true); const sale = await posApi.checkout(payload); await Promise.all([refreshProducts(), refreshCustomers()]); setLastCompletedSale(sale); setIsPaymentModalOpen(false); setIsReceiptModalOpen(true); setCartItems([]); setOverallDiscount(0); setSelectedCustomer(null); toast.success(`تم إصدار الفاتورة رقم ${sale.invoice_number} بنجاح!`); } catch (error) { toast.error(error.response?.data?.message || 'فشلت معالجة الفاتورة'); } finally { setIsCheckoutLoading(false); } };
  useEffect(() => { const keydown = (event) => { if (event.key === 'F2') { event.preventDefault(); if (cartItems.length) setIsPaymentModalOpen(true); } }; window.addEventListener('keydown', keydown); return () => window.removeEventListener('keydown', keydown); }, [cartItems.length]);
  const subtotalBeforeTax = cartItems.reduce((sum, item) => sum + (item.unit_price * item.quantity - item.discount_amount), 0); const totalTax = cartItems.reduce((sum, item) => sum + item.tax_amount, 0); const grandTotal = Math.max(0, subtotalBeforeTax + totalTax - overallDiscount);
  return <div className="h-[calc(100vh-5.5rem)] flex flex-col lg:flex-row gap-4 overflow-hidden"><div className="flex-1 h-full overflow-hidden flex flex-col"><PosProductGrid products={productsData?.data || []} categories={categories} onSelectProduct={addToCart} onBarcodeSubmit={handleBarcodeSubmit} isLoading={isProductsLoading} /></div><div className="w-full lg:w-96 xl:w-[420px] h-full flex flex-col"><PosCart items={cartItems} customer={selectedCustomer} onSelectCustomerClick={() => setIsPaymentModalOpen(true)} onQuickCustomerAdd={() => setIsQuickCustomerOpen(true)} onUpdateQuantity={updateQuantity} onRemoveItem={(id) => setCartItems((current) => current.filter((item) => item.product.id !== id))} onClearCart={clearCart} onHoldOrder={holdOrder} heldOrdersCount={heldOrders.length} onOpenHeldOrders={() => setIsHeldOrdersOpen(true)} overallDiscount={overallDiscount} onSetOverallDiscount={setOverallDiscount} onOpenPaymentModal={() => setIsPaymentModalOpen(true)} /></div>{isPaymentModalOpen && <PaymentModal isOpen={isPaymentModalOpen} onClose={() => setIsPaymentModalOpen(false)} grandTotal={grandTotal} customer={selectedCustomer} customers={customers} onSelectCustomer={setSelectedCustomer} onConfirmCheckout={checkout} isLoading={isCheckoutLoading} />}{isReceiptModalOpen && <ReceiptModal isOpen={isReceiptModalOpen} onClose={() => setIsReceiptModalOpen(false)} sale={lastCompletedSale} onNewSale={() => { setLastCompletedSale(null); setIsReceiptModalOpen(false); }} />}{isQuickCustomerOpen && <QuickCustomerModal isOpen={isQuickCustomerOpen} onClose={() => setIsQuickCustomerOpen(false)} onCustomerCreated={async (customer) => { await refreshCustomers(); setSelectedCustomer(customer); }} />}{isHeldOrdersOpen && <HeldOrdersModal isOpen={isHeldOrdersOpen} onClose={() => setIsHeldOrdersOpen(false)} heldOrders={heldOrders} onResumeOrder={resumeOrder} onDeleteOrder={(id) => { setHeldOrders((current) => current.filter((item) => item.id !== id)); toast.info('تم حذف الفاتورة من المعلقات'); }} />}{isClearConfirmOpen && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4"><div className="w-full max-w-sm bg-slate-900 border border-slate-700 rounded-2xl shadow-2xl p-6 space-y-4"><h3 className="font-bold text-slate-100 text-sm">مسح جميع عناصر السلة؟</h3><p className="text-xs text-slate-400">سيتم حذف جميع الأصناف والخصومات من الفاتورة الحالية.</p><div className="flex items-center justify-end gap-2 pt-2"><Button variant="outline" size="sm" onClick={() => setIsClearConfirmOpen(false)}>تراجع</Button><Button size="sm" onClick={confirmClearCart} className="bg-rose-600 hover:bg-rose-700 text-white">مسح السلة</Button></div></div></div>}</div>;
}
